job_name: order_count_by_quarter_product_category
source_tables:
  - olist_orders_raw
  - olist_order_items_raw
  - olist_products_raw
  - olist_category_translation_raw
target_table: gold.order_count_by_quarter_product_category
bronze_format: csv
