"""
US-001 — Monthly Revenue Summary by Product Category
Generated by Coding Agent from ETLSpec: gold.monthly_revenue_summary
"""
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

CATALOG = "olist_ecommerce"
BRONZE = f"{CATALOG}.bronze"
GOLD = f"{CATALOG}.gold"
TARGET = f"{GOLD}.monthly_revenue_summary"


def build_monthly_revenue_summary(spark: SparkSession):
    orders = spark.table(f"{BRONZE}.olist_orders_raw")
    items = spark.table(f"{BRONZE}.olist_order_items_raw")
    products = spark.table(f"{BRONZE}.olist_products_raw")
    translation = spark.table(f"{BRONZE}.olist_category_translation_raw")

    base = (
        orders.alias("o")
        .join(items.alias("i"), "order_id")
        .join(products.alias("p"), "product_id")
        .join(translation.alias("t"), "product_category_name", "left")
        .filter(F.col("o.order_status") == "delivered")
        .filter(F.col("i.price").isNotNull())
        .filter(F.col("o.order_purchase_timestamp").isNotNull())
    )

    with_dates = base.withColumn("order_year", F.year("o.order_purchase_timestamp")).withColumn(
        "order_month", F.month("o.order_purchase_timestamp")
    )

    result = (
        with_dates.groupBy("order_year", "order_month", "t.product_category_name_english")
        .agg(
            F.sum("i.price").alias("total_revenue"),
            F.count("o.order_id").alias("total_orders"),
            F.avg("i.price").alias("avg_order_value"),
        )
        .filter(F.col("product_category_name_english").isNotNull())
    )

    result.write.format("delta").mode("overwrite").saveAsTable(TARGET)
    return result


def main():
    spark = SparkSession.builder.appName("US001_monthly_revenue_summary").getOrCreate()
    build_monthly_revenue_summary(spark)


if __name__ == "__main__":
    main()
